# Generated by Django 4.0 on 2022-01-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(max_length=2048, unique=True)),
                ('name', models.CharField(max_length=350)),
                ('price', models.FloatField()),
            ],
        ),
    ]
