# Generated by Django 4.0 on 2022-01-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
